Added ampersand in front of Notepad++
notepad-plus-plus/nppShell pull request #40
Opened 2023-07-18 11:54 UTC by GurliGebis

This enables the N shortcut key in the old/classic right click menu.
The new Windows 11 menu does not support shortcut keys.

This fixes notepad-plus-plus#13678

2023-07-18 13:13 UTC, Susko3 requested changes

2023-07-18 14:36 UTC, GurliGebis commented on NppShell.rc
> +            VALUE "ProductName", "&Notepad++"
Indeed you are right - I was a bit too fast with search/replace - I'll fix.
Thanks

2023-07-18 22:48 UTC, closed without merging

2023-07-18 22:49 UTC, donho commented
@GurliGebis 
Next time please add date into the branch name for making sure the branch name of PR is unique.

2023-07-19 05:18 UTC, GurliGebis commented
@donho will do 👍

2023-07-28 16:19 UTC, oo777 commented
Great thanks!

2023-07-28 16:21 UTC, oo777 commented
Great, thanks for bringing this back! When will this be included and do we have to reinstall notepad++?

2023-07-28 21:13 UTC, GurliGebis commented
@oo777 in the next release of Notepad++, you will just have to upgrade (explorer might need to restart before the new DLL is loaded into it's memory)